backend:
  image: __PLACEHOLDER_OVERRIDE_ME__
  port: 8000
  replicas: 1
  strategy: RollingUpdate

frontend:
  image: __PLACEHOLDER_OVERRIDE_ME__
  port: 8501
  replicas: 1
  strategy: RollingUpdate

database:
  # TA Note: MySQL로 바꾸려면 여기 image와 port만 바꾼다.
  # 차트에 MySQL용 설정값들도 미리 대응되어 있음.
  # 학생들이 Database에 접근할 때는 Backend에 주입되는 다음 ENV를 사용하도록 가이드한다.
  # - DATABASE_HOST
  # - DATABASE_PORT
  # - DATABASE_USER
  # - DATABASE_PASSWORD
  image: postgres:16.2
  port: 5432
  replicas: 1
  strategy: Recreate
  username: mobilex
  dbname: mobilex

nginx:
  # TA Note: Nginx은 미리 다음과 같이 설정되어 있다.
  # - Frontend 접근 시: 별도 prefix 없음
  # - Backend 접근 시: /api prefix 사용
  # 변경하려면 차트에서 손을 보아야 한다.
  image: nginx:1.25.5
  port: 80
  replicas: 1
  strategy: RollingUpdate
